serverAddr = "18.179.12.207"
serverPort = 7000
vhostHTTPPort = 8081

[[proxies]]
name = "ssh2"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

[[proxies]]
name = "web2"
type = "http"
localPort = 8000
remotePort = 8081
customDomains = ["18.179.12.207"]
