name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag afterlifexx/upc-system:1.0

      - name: Build the Docker image for backend
        run: docker build ./backend/UPC-API --file ./backend/UPC-API/Dockerfile --tag afterlifexx/upc-api:1.0

      - name: Build the Docker image for frontend
        run: docker build ./frontend/upc-react --file ./frontend/upc-react/Dockerfile --tag afterlifexx/upc-react:1.0

      - name: Build the Docker image for Register Service
        run: docker build ./register-server --file ./register-server/Dockerfile --tag afterlifexx/upc-register:1.0

      - name: Push the Docker image to the Dockerhub
        run: docker push afterlifexx/upc-system:1.0

      - name: Push the Docker image for backend to the Dockerhub
        run: docker push afterlifexx/upc-api:1.0

      - name: Push the Docker image for frontend to the Dockerhub
        run: docker push afterlifexx/upc-react:1.0

      - name: Push the Docker image for Register Service to the Dockerhub
        run: docker push afterlifexx/upc-register:1.0
